### ISSUE TITLE
make the app also usable for pebble time round

### ISSUE THREAD

**Issue by Coollision** [kristofwillen/Pebble-NMBS#11]
i've taken a look at your code and I think it is just as easy as changing the settings so that it wil also be build for a pebble time round

**Comment by kristofwillen** [comment]
Has been fixed in v1.2.  I'll push it to the AppStore soon.

**Comment by kristofwillen** [comment]
Uploaded to AppStore.  Messages may sometimes a bit off the screen, but I made sure this should only be a minor cosmetic issue.

**Comment by Coollision** [comment]
Thanks

**Comment by kristofwillen** [comment]
Released v1.3 which fixes a bug in the PTR detection, as well as support for (unofficial) PTR polished Gold/Silver  models.
