### ISSUE TITLE
Add support for multiple destinations

### ISSUE THREAD

**Issue by Hipska** [kristofwillen/Pebble-NMBS#3]
Make it possible to be able to add multiple start-end combinations for different routes you do a lot.

Example:
- Brugge - Gent
- Aalter - Gent
- Aalter - Antwerpen
- ...

Maybe limitation to a fixed number of routes (both directions)

**Comment by kristofwillen** [comment]
I'm thinking of implementing this as such:
- on the config page, you can enter up to 4 favorite train stations (at least 2 obligatory)
- when you start the app, you'll see a screen where you must select your departure station from the list of 4
- after that, you must select your destination. 
- the list of available trains for your trajectory is shown.

This means some more 'clicking', but this seems the only flexible solution.

**Comment by Hipska** [comment]
Seems reasonable for me.

**Comment by Hipska** [comment]
And make sure they are in a fixed order an not sorted alphabetically, this way you can enter the stations you use most first.

**Comment by kristofwillen** [comment]
Fixed in v1.0, available on the pebble appstore.  You need to re-enter your config, sorry about that, but both versions are incompatible.
