### ISSUE TITLE
App crashes when started

### ISSUE THREAD

**Issue by liezie** [kristofwillen/Pebble-NMBS#8]
The app starts, asks the destination.
I fill in the destination. Upon entering, the app crashes. 

This is a pebble classic. It's updated and the app is on version 0.6

**Comment by kristofwillen** [comment]
Is this reproducible ? Once you filled in the start/destination, can you successfully run the app ?

**Comment by liezie** [comment]
Yes, always reproducable. The app simply wont go any further.
I get the screen where it asks destination, when i click a button it
crashes.

So, i went to the phone and filled in my default destination in the betrain
configuration page.
Then returned to the pebble, start the app.
Now my destination ('bestemming') is filled in. When i press select button,
it crashes again.

Maybe i'm using it wrong?

Is there any information i can retrieve that would be useful to you?

**Comment by kristofwillen** [comment]
1. Are you sure the stations names you entered on the config page are correct (see iRail site http://irail.be/stations/NMBS ) ?
2. Could you do the following 
   a. deinstall the app
   b. reinstall the app from the appstore. It will start on your Pebble. Exit it
   c. On your phone the config page will open.  Enter the start/stop stations.  Save
   d. start the app.  Does it crash again  ?

**Comment by liezie** [comment]
yes, now it works. :)
i had only put a start station in my settings.  so it probably crashed
because it had no value in the stop-field.

do i understand correctly that i can only see the trains between two fixed
stations?
i don't mind having to preset some stations, but 2 is a bit limiting.

i'll log a feature request tonight: increase number of possible stations to
at least 4. :-)

**Comment by kristofwillen** [comment]
Yes, you can only specify 2 stations (start/stop).  When you choose a destination station, the other is automatically selected as starting station.  This is a current limitation. 

If you want multiple stations supported, the app should add a screen for a starting station where you can choose out of some presets, and another screen for destination.  

There's already a feature request open for support for multiple destinations:
https://github.com/kristofwillen/Pebble-NMBS/issues/3

**Comment by liezie** [comment]
nothing left for me to do then. thanks!

**Comment by kristofwillen** [comment]
Added some changes (CSS/text) on the config screen which hopefully should make the above more clear. 

Closing this report.
